os:
  - linux
  - osx

env:
  - NODE_VERSION=4
  - NODE_VERSION=5

addons:
  apt:
    packages:
      - build-essential
      - clang
      - libdbus-glib-1-dev
      - libgtk2.0-dev
      - libnotify-dev
      - libgnome-keyring-dev
      - libgconf2-dev
      - libasound2-dev
      - libcap-dev
      - libcups2-dev
      - libxtst-dev
      - libxss1
      - libnss3-dev
      - gcc-multilib
      - g++-multilib
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm --version
  - node --version
  - npm --version
  - npm install

script:
  - npm test

cache:
  directories:
  - node_modules

notifications:
  email: false
